# version: "3.9"
# docker-compose run --rm app sh -c "python manage.py runserver 0.0.0.0:8000"
# docker compose run --rm --service-ports app sh -c "python manage.py runserver 0.0.0.0:8000"
# docker compose run up
# docker compose build

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - my_network

volumes:
  dev-db-data:
networks:
  my_network:
