# Generated by Django 5.1.7 on 2025-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_cash',
            field=models.IntegerField(default=0, help_text='총 캐시'),
        ),
    ]
