# Generated by Django 4.2 on 2025-03-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='포토카드 명', max_length=100)),
                ('artist_name', models.CharField(help_text='아티스트 명', max_length=30)),
                ('group_name', models.CharField(default='', help_text='아티스트 그룹명', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
