# Generated by Django 4.2 on 2025-03-15 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('cash', models.IntegerField(help_text='적립/사용 캐시 (+는 적립, -는 사용으로 가정)')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='이력 발생 일시')),
                ('user_id', models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
