# Generated by Django 4.2 on 2025-03-15 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(help_text='등록 수량')),
                ('price', models.PositiveIntegerField(help_text='장 당 가격')),
                ('photo_card_id', models.ForeignKey(help_text='포토카드 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='inventory.photocard')),
                ('user_id', models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
