# Generated by Django 4.2 on 2025-03-16 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(help_text='구매 수량')),
                ('sale_id', models.ForeignKey(help_text='판매 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='buys', to='transactions.sale')),
                ('user_id', models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='buys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
