# Generated by Django 4.2.15 on 2025-03-18 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('REQUESTED', '요청'), ('DELIVERED', '배송완료'), ('CANCELLED', '취소')], default='REQUESTED', help_text='배송 상태', max_length=10)),
                ('address', models.CharField(help_text='배송 주소', max_length=255)),
                ('postal_code', models.CharField(help_text='우편번호', max_length=5)),
                ('buy_id', models.ForeignKey(help_text='구매 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_requests', to='transactions.buy')),
                ('user_id', models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
